[package]
name = "restsend-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.59", features = ["full", "fold"] }
quote = "1.0.36"
proc-macro2 = "1.0.80"
