[workspace]
resolver = "2"
members = ["crates/restsend", "crates/restsend-ffi", "crates/demo"]

[profile.dev.package."*"]
opt-level = 2

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1
