[package]
name = "restsend-wasm"
version = "1.0.0"
edition = "2021"
description = "A client for the retsend server"

[lib]
crate-type = ["cdylib"]

[features]
default = ["conversation", "topic", "message"]
conversation = []
topic = []
message = []

[dependencies]
serde = "1.0.193"
restsend-sdk = { path = "../restsend", features = ["web"] }
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4.39"
futures-util = "0.3.29"
futures = "0.3.29"
js-sys = "0.3.66"
web-sys = "0.3.66"
chrono = "0.4.31"
serde-wasm-bindgen = "0.6.3"
log = "0.4.20"
[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[profile.release]
lto = true
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = true
