[package]
name = "restsend-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
uniffi = { version = "0.25.2", features = ["build", "cli"] }
uniffi_bindgen = "0.25.2"
reqwest = { version = "0.11.22", default-features = false, features = [
    "json",
    "multipart",
    "stream",
    "native-tls",
] }
tokio = { version = "1.34.0", features = ["full"] }
tokio-util = "0.7.9"
rusqlite = { version = "0.30.0", features = ["bundled"] }
lazy_static = "1.4.0"
include_dir = "0.7.3"
lru = "0.12.1"
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
log = "0.4.20"
tokio-websockets = { version = "0.4.1", features = [
    "native-tls",
    "client",
    "openssl",
    "rand",
] }
url = "2.5.0"
futures-channel = "0.3.29"
futures-util = { version = "0.3.29", features = ["sink", "std"] }
http = "1.0.0"
base64 = "0.21.5"
rand = "0.8.5"
thiserror = "1.0.50"
env_logger = "0.10.1"
chrono = "0.4.31"
#tokio-task-pool = "0.1.5"
md5 = "0.7.0"
clap = "4.4.11"
camino = "1.1.6"
tempdir = "0.3.7"

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
openssl = { version = "0.10.61", features = ["vendored"] }

[dev-dependencies]
hyper = { version = "1.0.1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1.1", features = ["full"] }
tempfile = "3.8.1"
multer = "2.1.0"

[profile.release]
opt-level = "z"
strip = "debuginfo"
lto = true

[[bin]]
name = "bindgen"
path = "bindgen.rs"
